// MagicPatterns/Proyecto con prompt largo/src/components/PriceListSection.tsx
import React from 'react';
import { Clock, Scissors } from 'lucide-react';
// Price item component
const PriceItem = ({
  service,
  price,
  duration,
  isPremium = false
}) => {
  return <div className={`p-4 border-b ${isPremium ? 'bg-neutral-100 rounded-md' : ''}`}>
      <div className="flex justify-between items-start">
        <div>
          <h3 className="font-medium text-lg">{service}</h3>
          <p className="text-neutral-600 flex items-center mt-1">
            <Clock size={16} className="mr-1" /> Aprox. {duration} min
          </p>
        </div>
        <div className="text-xl font-semibold">{price}€</div>
      </div>
    </div>;
};
export const PriceListSection = () => {
  const services = [{
    service: 'Corte Clásico',
    price: 20,
    duration: 25
  }, {
    service: 'Fade Completo',
    price: 25,
    duration: 30,
    isPremium: true
  }, {
    service: 'Corte + Afeitado',
    price: 30,
    duration: 45,
    isPremium: true
  }, {
    service: 'Afeitado Tradicional',
    price: 15,
    duration: 20
  }, {
    service: 'Recorte de Barba',
    price: 12,
    duration: 15
  }, {
    service: 'Peinado y Styling',
    price: 10,
    duration: 10
  }, {
    service: 'Tratamiento Capilar',
    price: 35,
    duration: 40,
    isPremium: true
  }, {
    service: 'Corte Infantil',
    price: 15,
    duration: 20
  }];
  return <section id="services" className="py-16 bg-white">
      <div className="container mx-auto px-6">
        <h2 className="text-3xl font-bold mb-4 text-center">
          Servicios y Precios
        </h2>
        <p className="text-center text-neutral-600 mb-12 max-w-2xl mx-auto">
          Ofrecemos una amplia gama de servicios de barbería profesional a
          precios competitivos.
        </p>
        <div className="max-w-3xl mx-auto">
          <div className="grid grid-cols-1 gap-2">
            {services.map((item, index) => <PriceItem key={index} {...item} />)}
          </div>
          <p className="mt-6 text-sm text-neutral-500 italic">
            * Los tiempos pueden variar según tipo de cabello. Consulta si
            necesitas un servicio personalizado.
          </p>
        </div>
      </div>
    </section>;
};

// src/app/components/price-list-section/price-list-section.component.ts
// src/app/components/price-list-section/price-list-section.component.ts
import { Component } from '@angular/core';

interface Service {
  name: string;
  price: string;
  duration: string;
  premium?: boolean;
}

@Component({
  selector: 'app-price-list-section',
  templateUrl: './price-list-section.component.html',
})
export class PriceListSectionComponent {
  services: Service[] = [
    { name: 'Corte clásico', price: '20€', duration: '25 min' },
    { name: 'Fade completo', price: '25€', duration: '30 min', premium: true },
    { name: 'Corte + Afeitado', price: '30€', duration: '45 min', premium: true },
    { name: 'Recorte de barba', price: '15€', duration: '15 min' },
    { name: 'Corte infantil', price: '18€', duration: '20 min' },
  ];
}

<!-- src/app/components/price-list-section/price-list-section.component.html -->
<section id="prices" class="py-16 bg-white">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
    <h2 class="text-3xl font-bold text-center mb-8">Precios y Tiempos</h2>
    <ul>
      <li *ngFor="let s of services" class="flex justify-between items-center py-4 border-b">
        <div>
          <span [ngClass]="{'font-semibold': s.premium}" class="text-lg">{{ s.name }}</span>
        </div>
        <div>
          <span class="text-lg">{{ s.price }}</span>
          <span class="text-gray-500 ml-2">({{ s.duration }})</span>
        </div>
      </li>
    </ul>
    <p class="text-sm text-gray-500 mt-4">
      Los tiempos pueden variar según tipo de cabello. Consulta si necesitas un servicio personalizado.
    </p>
  </div>
</section>
