// MagicPatterns/Proyecto con prompt largo/src/components/Header.tsx
import React from 'react';
import { Clock, MapPin, Phone } from 'lucide-react';
// Helper function to check if the barbershop is currently open
const isBarberShopOpen = () => {
  // This is a placeholder function - in a real implementation,
  // you would check current day and time against opening hours
  const now = new Date();
  const day = now.getDay(); // 0 is Sunday, 1 is Monday, etc.
  const hour = now.getHours();
  // Example logic: Open Monday-Friday 10:00-20:00, Saturday 9:00-18:00, closed Sunday
  if (day === 0) return false; // Closed on Sunday
  if (day === 6) return hour >= 9 && hour < 18; // Saturday 9:00-18:00
  return hour >= 10 && hour < 20; // Monday-Friday 10:00-20:00
};
// Helper function to get next opening time if closed
const getNextOpeningTime = () => {
  const now = new Date();
  const day = now.getDay();
  // This is simplified logic - you would expand this based on actual opening days/hours
  if (day === 0) {
    // If Sunday, open Monday
    return 'Reabrimos el Lunes a las 10:00';
  } else if (day === 6 && now.getHours() >= 18) {
    // If Saturday after closing
    return 'Reabrimos el Lunes a las 10:00';
  } else {
    // For other days, reopen tomorrow
    return 'Reabrimos mañana a las 10:00';
  }
};
export const Header = () => {
  const isOpen = isBarberShopOpen();
  return <header className="w-full">
      {/* Top bar with announcement */}
      <div className="bg-black text-white text-center py-2 text-sm">
        <p>Próximamente: reservas online y pago telemático</p>
      </div>
      {/* Navigation */}
      <nav className="bg-white py-4 px-6 flex items-center justify-between border-b">
        <div className="flex items-center">
          {/* Replace with actual logo */}
          <h1 className="text-2xl font-bold">BARBERÍA MODERNA</h1>
        </div>
        <div className="hidden md:flex items-center space-x-6">
          <a href="#location" className="text-neutral-700 hover:text-black flex items-center">
            <MapPin size={16} className="mr-1" /> Ubicación
          </a>
          <a href="#services" className="text-neutral-700 hover:text-black flex items-center">
            <Clock size={16} className="mr-1" /> Servicios
          </a>
          <a href="#contact" className="text-neutral-700 hover:text-black flex items-center">
            <Phone size={16} className="mr-1" /> Contacto
          </a>
        </div>
        <div className="flex items-center">
          <div className={`px-3 py-1 rounded-full text-white text-sm font-medium ${isOpen ? 'bg-green-500' : 'bg-red-500'}`}>
            {isOpen ? 'Abierto' : 'Cerrado'}
          </div>
        </div>
      </nav>
      {/* Hero Section */}
      <div className="relative h-[80vh] bg-cover bg-center flex items-center" style={{
      backgroundImage: "linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1503951914875-452162b0f3f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80')"
    }}>
        <div className="container mx-auto px-6">
          <div className="max-w-xl">
            <h1 className="text-5xl font-bold text-white mb-4">
              Estilo y Precisión en Cada Corte
            </h1>
            <p className="text-xl text-gray-200 mb-8">
              La barbería de referencia para el hombre moderno. Cortes clásicos
              con un toque contemporáneo.
            </p>
            {/* Open/Closed Status with next opening time */}
            <div className="mb-8">
              <div className={`inline-flex items-center px-4 py-2 rounded-md ${isOpen ? 'bg-green-500' : 'bg-red-500'} text-white font-medium`}>
                {isOpen ? 'Abierto Ahora' : 'Cerrado'}
              </div>
              {!isOpen && <p className="text-white mt-2">{getNextOpeningTime()}</p>}
            </div>
            <div className="flex flex-wrap gap-4">
              <a href="#booking" className="bg-white text-black px-6 py-3 rounded-md font-medium hover:bg-gray-100 transition">
                Reserva tu cita
              </a>
              <a href="#featured" className="bg-transparent text-white border border-white px-6 py-3 rounded-md font-medium hover:bg-white hover:text-black transition">
                Ver nuestros cortes
              </a>
            </div>
          </div>
        </div>
      </div>
    </header>;
};

// src/app/components/header/header.component.ts
// src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { IconClock, IconMapPin, IconPhone } from 'lucide-angular';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
})
export class HeaderComponent implements OnInit {
  isOpen: boolean;
  nextOpenText: string;

  ngOnInit() {
    this.checkOpenStatus();
  }

  private checkOpenStatus() {
    const now = new Date();
    const day = now.getDay(); // 0 Sunday, 1 Monday, …
    const hour = now.getHours();
    let open = false;
    if (day === 0) {
      open = false;
      this.nextOpenText = this.getNextOpeningTime();
    } else if (day === 6) {
      open = hour >= 9 && hour < 18;
      if (!open) this.nextOpenText = this.getNextOpeningTime();
    } else {
      open = hour >= 10 && hour < 20;
      if (!open) this.nextOpenText = this.getNextOpeningTime();
    }
    this.isOpen = open;
  }

  private getNextOpeningTime(): string {
    const now = new Date();
    let next = new Date(now);
    const day = now.getDay();
    const hour = now.getHours();
    // If Sunday → next is Monday at 10:00
    if (day === 0) {
      next.setDate(now.getDate() + 1);
      next.setHours(10, 0, 0, 0);
      return `Reabrimos el ${this.formatDate(next)} a las ${this.formatHour(next)}`;
    }
    // Saturday after 18:00 → next Monday at 10:00
    if (day === 6 && hour >= 18) {
      next.setDate(now.getDate() + 2);
      next.setHours(10, 0, 0, 0);
      return `Reabrimos el ${this.formatDate(next)} a las ${this.formatHour(next)}`;
    }
    // Weekday before 10:00 → hoy a las 10:00
    if (day >= 1 && day <= 5 && hour < 10) {
      next.setHours(10, 0, 0, 0);
      return `Reabrimos hoy a las 10:00`;
    }
    // Weekday after 20:00 → mañana a las 10:00 (except si mañana domingo)
    if (day >= 1 && day <= 5 && hour >= 20) {
      if (day === 5) {
        // Viernes después de cierre → sábado a las 9:00
        next.setDate(now.getDate() + 1);
        next.setHours(9, 0, 0, 0);
        return `Reabrimos el ${this.formatDate(next)} a las 9:00`;
      } else {
        next.setDate(now.getDate() + 1);
        next.setHours(10, 0, 0, 0);
        return `Reabrimos mañana a las 10:00`;
      }
    }
    // Sábado antes de 9:00 → hoy a las 9:00
    if (day === 6 && hour < 9) {
      next.setHours(9, 0, 0, 0);
      return `Reabrimos hoy a las 9:00`;
    }
    return '';
  }

  private formatDate(d: Date): string {
    const dd = String(d.getDate()).padStart(2, '0');
    const mm = String(d.getMonth() + 1).padStart(2, '0');
    const yyyy = d.getFullYear();
    return `${dd}/${mm}/${yyyy}`;
  }

  private formatHour(d: Date): string {
    const hh = String(d.getHours()).padStart(2, '0');
    const mi = String(d.getMinutes()).padStart(2, '0');
    return `${hh}:${mi}`;
  }
}

<!-- src/app/components/header/header.component.html -->
<header class="bg-black text-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center py-6">
      <div class="flex items-center gap-4">
        <img src="assets/logo.png" alt="Logo" class="h-10" />
        <div class="flex items-center gap-2">
          <ng-container *ngIf="isOpen; else closedTpl">
            <span class="text-green-400 font-medium">Abierto</span>
          </ng-container>
          <ng-template #closedTpl>
            <span class="text-red-500 font-medium">Cerrado</span>
            <p class="text-white mt-1">{{ nextOpenText }}</p>
          </ng-template>
        </div>
      </div>
      <div class="flex flex-wrap gap-4">
        <a href="#booking"
           class="bg-white text-black px-6 py-3 rounded-md font-medium hover:bg-gray-100 transition">
          Reserva tu cita
        </a>
        <a href="#featured"
           class="bg-transparent text-white border border-white px-6 py-3 rounded-md font-medium hover:bg-white hover:text-black transition">
          Ver nuestros cortes
        </a>
      </div>
    </div>
  </div>
</header>
