// src/app/components/footer/footer.component.ts
// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
})
export class FooterComponent {}

<!-- src/app/components/footer/footer.component.html -->
<footer class="bg-black text-white py-8">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 md:grid-cols-3 gap-8">
    <div>
      <h3 class="text-xl font-semibold mb-2">Contacto</h3>
      <p>Calle Falsa 123, Ciudad, País</p>
      <p class="mt-1"><a href="tel:+34600000000" class="hover:underline">+34 600 000 000</a></p>
      <p class="mt-1"><a href="mailto:info@barberia.com" class="hover:underline">info@barberia.com</a></p>
    </div>
    <div>
      <h3 class="text-xl font-semibold mb-2">Síguenos</h3>
      <div class="flex items-center gap-4">
        <a href="#" aria-label="Instagram" class="hover:text-gray-400">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
            <path d="M7.75 2h8.5A5.75 5.75 0 0 1 22 7.75v8.5A5.75 5.75 0 0 1 16.25 22h-8.5A5.75 5.75 0 0 1 2 16.25v-8.5A5.75 5.75 0 0 1 7.75 2zm0 1.5A4.25 4.25 0 0 0 3.5 7.75v8.5A4.25 4.25 0 0 0 7.75 20.5h8.5A4.25 4.25 0 0 0 20.5 16.25v-8.5A4.25 4.25 0 0 0 16.25 3.5h-8.5z" />
            <path d="M12 7.5a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9zm0 1.5a3 3 0 1 0 0 6 3 3 0 0 0 0-6zM16.25 7a.75.75 0 1 1 0 1.5A.75.75 0 0 1 16.25 7z" />
          </svg>
        </a>
        <a href="#" aria-label="Facebook" class="hover:text-gray-400">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
            <path d="M22 12a10 10 0 1 0-11.54 9.88v-6.99h-2.33v-2.9h2.33V9.79c0-2.3 1.37-3.57 3.47-3.57.99 0 2.03.18 2.03.18v2.23h-1.14c-1.12 0-1.47.7-1.47 1.42v1.7h2.5l-.4 2.9h-2.1V22A10 10 0 0 0 22 12z" />
          </svg>
        </a>
        <a href="#" aria-label="Google My Business" class="hover:text-gray-400">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
            <path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm1 14.5h-2v-2h2v2zm0-4h-2V7h2v5.5z" />
          </svg>
        </a>
      </div>
    </div>
    <div>
      <h3 class="text-xl font-semibold mb-2">Legal</h3>
      <ul>
        <li><a href="#" class="hover:underline">Política de privacidad</a></li>
        <li class="mt-1"><a href="#" class="hover:underline">Términos y condiciones</a></li>
      </ul>
    </div>
  </div>
</footer>

// MagicPatterns/Proyecto con prompt largo/src/components/Footer.tsx
import React from 'react';
import { MapPin, Phone, Mail, Instagram, Facebook } from 'lucide-react';
export const Footer = () => {
  return <footer id="contact" className="bg-black text-white pt-16 pb-8">
      <div className="container mx-auto px-6">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {/* Contact Info */}
          <div>
            <h3 className="text-xl font-bold mb-4">Contacto</h3>
            <div className="flex items-center mb-3">
              <MapPin size={18} className="mr-2" />
              <p>Calle Falsa 123, Ciudad, País</p>
            </div>
            <div className="flex items-center mb-3">
              <Phone size={18} className="mr-2" />
              <a href="tel:+34600000000" className="hover:text-gray-300">
                +34 600 000 000
              </a>
            </div>
            <div className="flex items-center mb-3">
              <Mail size={18} className="mr-2" />
              <a href="mailto:info@barberiamoderna.com" className="hover:text-gray-300">
                info@barberiamoderna.com
              </a>
            </div>
          </div>
          {/* Hours */}
          <div>
            <h3 className="text-xl font-bold mb-4">Horario</h3>
            <div className="grid grid-cols-2 gap-2">
              <p className="text-gray-400">Lunes a Viernes:</p>
              <p>10:00–20:00</p>
              <p className="text-gray-400">Sábado:</p>
              <p>9:00–18:00</p>
              <p className="text-gray-400">Domingo:</p>
              <p>Cerrado</p>
            </div>
          </div>
          {/* Quick Links */}
          <div>
            <h3 className="text-xl font-bold mb-4">Enlaces</h3>
            <ul className="space-y-2">
              <li>
                <a href="#featured" className="hover:text-gray-300">
                  Nuestros Cortes
                </a>
              </li>
              <li>
                <a href="#services" className="hover:text-gray-300">
                  Servicios y Precios
                </a>
              </li>
              <li>
                <a href="#booking" className="hover:text-gray-300">
                  Reservar Cita
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-gray-300">
                  Política de Privacidad
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-gray-300">
                  Términos y Condiciones
                </a>
              </li>
            </ul>
          </div>
          {/* Social & Newsletter */}
          <div>
            <h3 className="text-xl font-bold mb-4">Síguenos</h3>
            <div className="flex space-x-4 mb-6">
              <a href="https://instagram.com" target="_blank" rel="noopener noreferrer" className="hover:text-gray-300">
                <Instagram size={24} />
              </a>
              <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="hover:text-gray-300">
                <Facebook size={24} />
              </a>
            </div>
          </div>
        </div>
        <div className="border-t border-gray-800 mt-12 pt-8 text-center text-gray-400 text-sm">
          <p>
            &copy; {new Date().getFullYear()} Barbería Moderna. Todos los
            derechos reservados.
          </p>
        </div>
      </div>
    </footer>;
};
