// MagicPatterns/Proyecto con prompt largo/src/components/FAQSection.tsx
import React, { useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';
// FAQ Item component
const FAQItem = ({
  question,
  answer
}) => {
  const [isOpen, setIsOpen] = useState(false);
  return <div className="border-b border-neutral-200">
      <button className="flex justify-between items-center w-full py-4 text-left font-medium" onClick={() => setIsOpen(!isOpen)}>
        <span>{question}</span>
        {isOpen ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
      </button>
      {isOpen && <div className="pb-4 text-neutral-600">
          <p>{answer}</p>
        </div>}
    </div>;
};
export const FAQSection = () => {
  const faqs = [{
    question: '¿Cómo reservo si aún no está habilitado el sistema online?',
    answer: 'Por teléfono, WhatsApp o viniendo directamente al local. En breve lanzaremos la opción de reservas online.'
  }, {
    question: '¿Se puede comprar productos si no vivo cerca?',
    answer: 'Sí, enviamos a toda España. Pregúntanos por WhatsApp para más detalles sobre envíos y disponibilidad.'
  }, {
    question: '¿Aceptan pagos con tarjeta o solo efectivo?',
    answer: 'Actualmente aceptamos ambos; pronto también pasarelas de pago online para reservas y compras en nuestra web.'
  }, {
    question: '¿Cuánto tiempo dura un corte de pelo completo?',
    answer: 'Dependiendo del tipo de corte, entre 25 y 45 minutos. Los servicios que incluyen barba pueden tomar hasta una hora.'
  }, {
    question: '¿Necesito cita previa o puedo ir sin reservar?',
    answer: 'Recomendamos reservar para evitar esperas, pero también atendemos sin cita previa según disponibilidad del momento.'
  }];
  return <section className="py-16 bg-neutral-100">
      <div className="container mx-auto px-6">
        <h2 className="text-3xl font-bold mb-12 text-center">
          Preguntas Frecuentes
        </h2>
        <div className="max-w-3xl mx-auto">
          {faqs.map((faq, index) => <FAQItem key={index} {...faq} />)}
        </div>
      </div>
    </section>;
};

// src/app/components/faq-section/faq-section.component.ts
// src/app/components/faq-section/faq-section.component.ts
import { Component } from '@angular/core';

interface FAQ {
  question: string;
  answer: string;
}

@Component({
  selector: 'app-faq-section',
  templateUrl: './faq-section.component.html',
})
export class FAQSectionComponent {
  faqs: FAQ[] = [
    {
      question: '¿Cómo reservo si aún no está habilitado el sistema online?',
      answer: 'Por teléfono, WhatsApp o viniendo directamente al local. En breve lanzaremos la opción de reservas online.',
    },
    {
      question: '¿Se puede comprar productos si no vivo cerca?',
      answer: 'Sí, enviamos a toda España. Pregúntanos por WhatsApp.',
    },
    {
      question: '¿Aceptan pagos con tarjeta o solo efectivo?',
      answer: 'Actualmente aceptamos ambos; pronto también pasarelas de pago online.',
    },
  ];
  toggleIndex: number | null = null;

  toggle(i: number) {
    this.toggleIndex = this.toggleIndex === i ? null : i;
  }
}

<!-- src/app/components/faq-section/faq-section.component.html -->
<section id="faq" class="py-16 bg-gray-50">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
    <h2 class="text-3xl font-bold text-center mb-8">Preguntas Frecuentes</h2>
    <div class="space-y-4">
      <div *ngFor="let f of faqs; let i = index" class="border rounded-lg overflow-hidden">
        <button (click)="toggle(i)"
                class="w-full flex justify-between items-center px-4 py-3 bg-white">
          <span class="text-lg font-medium">{{ f.question }}</span>
          <svg *ngIf="toggleIndex !== i" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v14m7-7H5" />
          </svg>
          <svg *ngIf="toggleIndex === i" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 12H5" />
          </svg>
        </button>
        <div *ngIf="toggleIndex === i" class="px-4 py-3 bg-gray-100">
          <p class="text-gray-700">{{ f.answer }}</p>
        </div>
      </div>
    </div>
  </div>
</section>
